//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrispyCupon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cupon
    {
        public int idcode { get; set; }
        public string sucursal { get; set; }
        public string cupon1 { get; set; }
        public System.DateTime vigencia { get; set; }
        public bool estatus { get; set; }
        public int user_genero { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> consumido { get; set; }
        public int cantidad { get; set; }
    }
}
